version: "3.7"

services:
  db:
    image: mariadb:10.6
    healthcheck:
      test: mysqladmin ping -h localhost --password=${DB_PASSWORD:?No DB_PASSWORD set}
      interval: 1s
      retries: 15
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mariadb-network

volumes:
  db-data:

networks:
  mariadb-network:
    name: ${MARIADB_NETWORK}-network
    attachable: true

# Note: set MARIADB_NETWORK and DB_PASSWORD